name = "[Packwiz] GG 2023"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea0bfa7bfefa1a10b74aa424ad8821d6f1290f810d2293ff3500852ed5062af1"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
