name = "Goliath Gaming 2023 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2458b8569223fd14117462f8e6d9178a8d8ffec35eeefec6ec7ab681b290a73"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
