name = "Goliath Gaming 2023 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7612f6e4b2b4ff2c0220330487065795708d5bda50625a85ab845cfd451833e8"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
