name = "Goliath Gaming 2023 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae4580f2a9f7a6cfe8de61a75d214b09baf5793d1caeb1f0c2fc1703dd524afb"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
