name = "GG23 personal"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "468eb39f1a23ef10535650128417ebf706f2f6d49323ca48e2e51e9036d62d98"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
