name = "[Packwiz] GG 2023"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21c51629c0e643b8acf6d1c43ff62dc376b74912f47952313bfefcdfa40ba430"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
