name = "Goliath Gaming 2023 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a936e8078208905379598f5baa02cad3b4098c19760c99f24d21c0211cceb95"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
