name = "[Packwiz] GG 2023"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ec2716362f6e94ae5a9a98fc80d92a2ee065b5a909ef1b86bbbf74edb1c8e11"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
