name = "[Packwiz] GG 2023"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eefb0a8603d4e01af4118ebca42f04c7a72b864313ef450caf5b3e09eb3f6d9"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
