name = "[Packwiz] GG 2023"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07d8cf2dfb914bb51ccddc3c749c5678ba4caab20d3ee196efd040c7c9a95eef"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
