name = "Goliath Gaming 2023 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11e8d71c7c3a5a7a9a16bd5e673e43ca93658ba10cb25fe0cd01400dfca6f188"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
