name = "GG23 personal"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd60bbeaeb6b02371ea90d0b5439cdd01fe99e2b400490f2143fb5cbf40a6e23"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
