name = "GG23 personal"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb639378c1d18310614944ff792bc81af99736e4e1721069d16d873be4400e62"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
