name = "GG23 personal"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8dc0166d3ef85d37df1e7d92362101e8372a90d57d910a807cba8cc132c489c"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
